name: bharatx_flutter_securityhelpers
description: A new flutter plugin project.
version: 1.0.2-alpha1
homepage: https://bharatx.tech/
repository: https://github.com/bharatx-in/bharatx_flutter_securityhelpers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.bharatx.bharatx_flutter_securityhelpers
        pluginClass: BharatxFlutterSecurityhelpersPlugin
